version: "2"
services:
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=drupal
      - MYSQL_HOME=/etc
    volumes:
      - ./.docker/etc/my.cnf:/etc/my.cnf
    hostname: dbhost
    expose:
      - "3306"
    network_mode: bridge

  solr:
    image: solr:5.3-alpine
    hostname: solr
    command: solr-create -c collection1 -d /myconfig
    volumes:
      - ./docroot/sites/all/modules/contrib/search_api_solr/solr-conf/5.x:/myconfig
    expose:
      - "8983"
    network_mode: bridge

  selenium:
    image: wernight/phantomjs
    command: phantomjs --webdriver=8910
    network_mode: bridge

  web:
    build:
      context: ./
      dockerfile: docker/apache-php/Dockerfile
    environment:
      - HOST_USER=${HOST_UID}:${HOST_GID}
      - HOST_OS=${HOST_OS}
    expose:
      - "80"
    volumes:
      - .:/var/www
    links:
      - db:dbhost
      - solr:solr
      - selenium:selenium
    hostname: drupal
    network_mode: bridge

