# Storage
filestore:
  image: civicactions/sshd
  environment:
    - HOST_USER=${HOST_UID}:${HOST_GID}
  volumes:
    - /var/www
db:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_DATABASE=drupal
    - MYSQL_HOME=/etc
  volumes:
    - ./.docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  expose:
    - "3306"

# Services
solr:
  image: solr:5.3-alpine
  hostname: solr
  command: solr-create -c collection1 -d /myconfig
  volumes:
    - ./docroot/sites/all/modules/contrib/search_api_solr/solr-conf/5.x:/myconfig
  expose:
    - "8983"
web:
  build: .docker/web
  command: /start.sh
  environment:
    - HOST_USER=${HOST_UID}:${HOST_GID}
  expose:
    - "80"
  volumes_from:
    - filestore
  links:
    - db:dbhost
    - solr:solr
  hostname: drupal

# File synchronizing
sync:
  image: civicactions/bg-sync
  volumes:
    - .:/source
  volumes_from:
    - filestore
  environment:
    - SYNC_DESTINATION=/var/www
    - SYNC_WAIT=20
    - SYNC_VERBOSE=1
