<?php

/**
 * @file
 * A wrapper module for a custom two-part date field handler for Views.
 *
 * Views smartdate provides a custom date format to Views, to allow
 * two different date formats to be applied to a field, based on an
 * offset from the current time.
 */

/**
 * Implements hook_views_api().
 */
function views_smartdate_views_api() {
  return array(
    'api' => '2.0',
    'path' => drupal_get_path('module', 'views_smartdate'),
  );
}

/**
 * Implements hook_views_data_alter().
 */
function views_smartdate_views_data_alter(&$data) {
  foreach ($data as $table => $config) {
    foreach ($config as $item => $item_config) {
      if (isset($item_config['field']) && !empty($item_config['field']['handler'])) {
        if ($item_config['field']['handler'] == 'views_handler_field_date') {
          $data[$table][$item]['field']['handler'] = 'views_smartdate_handler_field_date';
        }
      }
    }
  }

  return $data;
}

/**
 * Implements hook_views_handlers().
 */
function views_smartdate_views_handlers() {
  return array(
    'info' => array(
      'path' => drupal_get_path('module', 'views_smartdate') . '/handlers',
    ),
    'handlers' => array(
      'views_smartdate_handler_field_date' => array(
        'parent' => 'views_handler_field_date',
        'file' => 'views_smartdate_handler_field_date.inc',
      ),
    ),
  );
}
